export const tableRow = [
  {
    id: 1,
    userName: "Fanuel Haftu",
    role: "Admin",
    email: "fanuelhaftu@gmail.com",
    status: "active",
  },
  {
    id: 2,
    userName: "Million Tenkir",
    role: "Admin",
    email: "milliontenkir@gmail.com",
    status: "active",
  },
  {
    id: 3,
    userName: "Kedir Bashir",
    role: "sells",
    email: "kedirbashir@gmail.com",
    status: "active",
  },
  {
    id: 4,
    userName: "Amanuel Abera",
    role: "delivery",
    email: "amanuelabera@gmail.com",
    status: "active",
  },
  {
    id: 5,
    userName: "Belay Sisay",
    role: "client",
    email: "belaysisay@gmail.com",
    status: "negative",
  },
  {
    id: 6,
    userName: "Abdul Mejid",
    role: "sells",
    email: "kedirbashir@gmail.com",
    status: "active",
  },
  {
    id: 7,
    userName: "Almaze Ayana",
    role: "delivery",
    email: "amanuelabera@gmail.com",
    status: "active",
  },
  {
    id: 8,
    userName: "Hunda Alex",
    role: "client",
    email: "belaysisay@gmail.com",
    status: "negative",
  },
  {
    id: 9,
    userName: "Israel Degefu",
    role: "Admin",
    email: "fanuelhaftu@gmail.com",
    status: "active",
  },
  {
    id: 10,
    userName: "Chanyalew Kefbel",
    role: "Admin",
    email: "milliontenkir@gmail.com",
    status: "active",
  },
  {
    id: 11,
    userName: "Amanuel Mekonen",
    role: "sells",
    email: "kedirbashir@gmail.com",
    status: "active",
  },
  {
    id: 12,
    userName: "Israel Getachew",
    role: "delivery",
    email: "amanuelabera@gmail.com",
    status: "active",
  },
  {
    id: 13,
    userName: "Hafiz Belay",
    role: "client",
    email: "belaysisay@gmail.com",
    status: "negative",
  },
  {
    id: 14,
    userName: "Biruck Ketema",
    role: "sells",
    email: "kedirbashir@gmail.com",
    status: "active",
  },
  {
    id: 15,
    userName: "Lidya Melis",
    role: "delivery",
    email: "amanuelabera@gmail.com",
    status: "active",
  },
  {
    id: 16,
    userName: "Hussen Ismael",
    role: "client",
    email: "belaysisay@gmail.com",
    status: "negative",
  },
];
